---
 # pre_tasks:
    - name: Install Python if not already present.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - name: Gather facts after Python is definitely present.
      setup:
    - name: Install pip
      apt:
        name: python-pip
        update_cache: yes
        state: present
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Install Python if not already present.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - name: Gather facts after Python is definitely present.
      setup:
    - name: Install pip
      apt:
        name: python-pip
        update_cache: yes
        state: present
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Install dependency
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: Add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Check whether docker is active
      service:
        name: docker
        state: started
        enabled: yes