---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: docker_hosts
  gather_facts: no
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - dependancies    
    - interview_container

